import type { Config } from "tailwindcss";

export default {
  darkMode: ["class"],
  content: ["./pages/**/*.{ts,tsx}", "./components/**/*.{ts,tsx}", "./app/**/*.{ts,tsx}", "./src/**/*.{ts,tsx}"],
  prefix: "",
  theme: {
    container: {
      center: true,
      padding: "2rem",
      screens: {
        "2xl": "1400px",
      },
    },
    extend: {
      fontFamily: {
        sans: ["Inter", "sans-serif"],
        headline: ["Manrope", "sans-serif"],
        body: ["Manrope", "sans-serif"],
      },
      colors: {
        border: "hsl(var(--border))",
        input: "hsl(var(--input))",
        ring: "hsl(var(--ring))",
        background: "hsl(var(--background))",
        foreground: "hsl(var(--foreground))",
        primary: {
          DEFAULT: "hsl(var(--primary))",
          foreground: "hsl(var(--primary-foreground))",
        },
        secondary: {
          DEFAULT: "hsl(var(--secondary))",
          foreground: "hsl(var(--secondary-foreground))",
        },
        destructive: {
          DEFAULT: "hsl(var(--destructive))",
          foreground: "hsl(var(--destructive-foreground))",
        },
        muted: {
          DEFAULT: "hsl(var(--muted))",
          foreground: "hsl(var(--muted-foreground))",
        },
        accent: {
          DEFAULT: "hsl(var(--accent))",
          foreground: "hsl(var(--accent-foreground))",
        },
        popover: {
          DEFAULT: "hsl(var(--popover))",
          foreground: "hsl(var(--popover-foreground))",
        },
        card: {
          DEFAULT: "hsl(var(--card))",
          foreground: "hsl(var(--card-foreground))",
        },
        sidebar: {
          DEFAULT: "hsl(var(--sidebar-background))",
          foreground: "hsl(var(--sidebar-foreground))",
          primary: "hsl(var(--sidebar-primary))",
          "primary-foreground": "hsl(var(--sidebar-primary-foreground))",
          accent: "hsl(var(--sidebar-accent))",
          "accent-foreground": "hsl(var(--sidebar-accent-foreground))",
          border: "hsl(var(--sidebar-border))",
          ring: "hsl(var(--sidebar-ring))",
        },
        goji: {
          orange: "hsl(var(--goji-orange))",
          coral: "hsl(var(--goji-coral))",
          berry: "hsl(var(--goji-berry))",
          dark: "hsl(var(--goji-dark))",
          "text-muted": "hsl(var(--goji-text-muted))",
          "bg-hero": "hsl(var(--goji-bg-hero))",
          "bg-hero-2": "hsl(var(--goji-bg-hero-2))",
        },
        md: {
          primary: "hsl(var(--md-primary))",
          "primary-container": "hsl(var(--md-primary-container))",
          "on-primary": "hsl(var(--md-on-primary))",
          "on-surface": "hsl(var(--md-on-surface))",
          "on-surface-variant": "hsl(var(--md-on-surface-variant))",
          secondary: "hsl(var(--md-secondary))",
          "secondary-container": "hsl(var(--md-secondary-container))",
          "secondary-fixed": "hsl(var(--md-secondary-fixed))",
          tertiary: "hsl(var(--md-tertiary))",
          "tertiary-fixed": "hsl(var(--md-tertiary-fixed))",
          surface: "hsl(var(--md-surface))",
          "surface-bright": "hsl(var(--md-surface-bright))",
          "surface-container": "hsl(var(--md-surface-container))",
          "surface-container-high": "hsl(var(--md-surface-container-high))",
          "surface-container-low": "hsl(var(--md-surface-container-low))",
          outline: "hsl(var(--md-outline))",
          "outline-variant": "hsl(var(--md-outline-variant))",
          error: "hsl(var(--md-error))",
        },
        snow: {
          primary: "#000000",
          "color-1": "#3B82F6",
          "color-2": "#7B61FF",
          "black-100": "#000000",
          "black-80": "#333333",
          "black-40": "#666666",
          "black-20": "#999999",
          "black-10": "#CCCCCC",
          "black-4": "#F5F5F5",
          "white-100": "#FFFFFF",
          "white-80": "#CCCCCC",
          "white-40": "#666666",
          "white-20": "#333333",
          "white-10": "#1A1A1A",
          "white-4": "#0A0A0A",
          "bg-1": "#FFFFFF",
          "bg-2": "#F7F8FA",
          "bg-3": "#F0F1F3",
          "surface-1": "#FFFFFF",
          "surface-2": "#F7F8FA",
          "surface-3": "#EDEDF0",
          purple: "#7B61FF",
          indigo: "#6366F1",
          blue: "#3B82F6",
          cyan: "#06B6D4",
          mint: "#34D399",
          green: "#22C55E",
          yellow: "#EAB308",
          orange: "#F97316",
          red: "#EF4444",
        },
      },
      borderRadius: {
        lg: "var(--radius)",
        md: "calc(var(--radius) - 2px)",
        sm: "calc(var(--radius) - 4px)",
        "2xl": "1rem",
        "3xl": "1.5rem",
        full: "9999px",
      },
      boxShadow: {
        card: "var(--shadow-card)",
        button: "var(--shadow-button)",
      },
      keyframes: {
        "accordion-down": {
          from: { height: "0" },
          to: { height: "var(--radix-accordion-content-height)" },
        },
        "accordion-up": {
          from: { height: "var(--radix-accordion-content-height)" },
          to: { height: "0" },
        },
        "fade-in-up": {
          from: { opacity: "0", transform: "translateY(24px)" },
          to: { opacity: "1", transform: "translateY(0)" },
        },
      },
      animation: {
        "accordion-down": "accordion-down 0.2s ease-out",
        "accordion-up": "accordion-up 0.2s ease-out",
        "fade-in-up": "fade-in-up 0.7s ease forwards",
      },
    },
  },
  plugins: [require("tailwindcss-animate")],
} satisfies Config;
